/**
 * PlanView Component
 * Renders the execution plan generated by Jules, step-by-step notes/feedback inputs,
 * conflict radar warnings, and approval actions.
 */
export const PlanView = memo(({ activities, session, apiKey, onApprove, onSendFeedback, busy, allSessions = [], activitiesMap = {} }) => {
  const [stepNotes, setStepNotes]     = useState({}); // stepId → note string
  const [activeNote, setActiveNote]   = useState(null); // stepId currently expanded
  const [globalNote, setGlobalNote]   = useState("");
  const [sending, setSending]         = useState(false);
  const [sent, setSent]               = useState(false);

  // Find the most recent planGenerated activity
  const planAct = useMemo(() => {
    for (let i = activities.length - 1; i >= 0; i--) {
      if (activities[i].planGenerated?.plan) return activities[i];
    }
    return null;
  }, [activities]);

  const plan  = planAct?.planGenerated?.plan;
  const steps = plan?.steps || [];

  // Check if plan already approved in activity history (must be after the plan was generated)
  const approved = useMemo(() => {
    if (!planAct) return false;
    const planTs = parseDateMs(planAct.createTime);
    return activities.some(a => a.planApproved && parseDateMs(a.createTime) >= planTs);
  }, [activities, planAct]);

  const hasFeedback = globalNote.trim() || Object.values(stepNotes).some(n => n.trim());

  const buildFeedbackMessage = () => {
    const parts = ["Please revise the plan based on my feedback:"];
    const stepFeedback = steps
      .filter(st => stepNotes[st.id]?.trim())
      .map((st, i) => `Step ${i + 1} (${st.title}): ${stepNotes[st.id].trim()}`);
    if (stepFeedback.length) parts.push(...stepFeedback);
    if (globalNote.trim()) parts.push("Overall: " + globalNote.trim());
    return parts.join("\n");
  };

  const handleRequestRevision = async () => {
    if (!hasFeedback || sending) return;
    setSending(true);
    try {
      await onSendFeedback(buildFeedbackMessage());
      setStepNotes({});
      setGlobalNote("");
      setActiveNote(null);
      setSent(true);
      setTimeout(() => setSent(false), 3000);
    } finally { setSending(false); }
  };

  if (!plan) return (
    <div style={{textAlign:"center",padding:"50px 24px",fontFamily:"'JetBrains Mono',monospace",fontSize:13,color:T.textDim}}>
      {session.state === "PLANNING" ? "Jules is generating a plan…" : "No plan available"}
    </div>
  );

  const pendingApproval = session.state === "AWAITING_PLAN_APPROVAL";
  const annotatedCount  = Object.values(stepNotes).filter(n=>n.trim()).length;

  return (
    <div style={{paddingBottom:16}}>
      <ConflictRadar
        currentSource={session.sourceContext?.source}
        currentBranch={session.sourceContext?.githubRepoContext?.startingBranch}
        currentPrompt={session.prompt}
        allSessions={allSessions}
        activitiesMap={activitiesMap}
        currentSessionId={session.id}
        startTime={parseDateMs(session.createTime)}
      />

      {/* Plan header */}
      <div style={{
        marginBottom:14,padding:"10px 14px",borderRadius:7,
        background:approved?T.brandDim:pendingApproval?T.purpleDim:T.surfaceHi,
        border:`1px solid ${approved?T.brand+"40":pendingApproval?T.purple+"40":T.border}`,
      }}>
        <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:approved||!pendingApproval?0:8}}>
          <div style={{flex:1,fontFamily:"'JetBrains Mono',monospace",fontSize:12,fontWeight:700,
            color:approved?T.brand:pendingApproval?T.purple:T.muted,letterSpacing:"0.06em"}}>
            {approved?"✓ PLAN APPROVED":pendingApproval?"PLAN READY FOR REVIEW":"PLAN PREVIEW"}
          </div>
          <span style={{fontFamily:"'JetBrains Mono',monospace",fontSize:11,color:T.textDim}}>
            {steps.length} step{steps.length!==1?"s":""}
          </span>
        </div>
        {pendingApproval&&!approved&&(
          <div style={{fontFamily:"'IBM Plex Sans',sans-serif",fontSize:14,color:T.textDim,lineHeight:1.5}}>
            Review each step below. Tap a step to add feedback, then request a revision or approve.
          </div>
        )}
      </div>

      {/* Steps */}
      <div style={{display:"flex",flexDirection:"column",gap:6,marginBottom:16}}>
        {steps.map((st, i) => {
          const note     = stepNotes[st.id] || "";
          const isOpen   = activeNote === st.id;
          const hasNote  = note.trim().length > 0;

          return (
            <div key={st.id||i} style={{
              background:T.surface,border:`1px solid ${hasNote?T.amber+"50":T.border}`,
              borderLeft:`2px solid ${hasNote?T.amber:T.purple+"60"}`,
              borderRadius:6,overflow:"hidden",transition:"border-color .15s cubic-bezier(0.4, 0, 0.2, 1)",
            }}>
              {/* Step row */}
              <div style={{display:"flex",gap:10,alignItems:"flex-start",padding:"10px 12px"}}>
                <div style={{
                  width:24,height:24,borderRadius:4,flexShrink:0,marginTop:1,
                  background:hasNote?T.amberDim:T.purpleDim,
                  border:`1px solid ${hasNote?T.amber+"50":T.purple+"40"}`,
                  display:"flex",alignItems:"center",justifyContent:"center",
                  fontFamily:"'JetBrains Mono',monospace",fontSize:11,fontWeight:700,
                  color:hasNote?T.amber:T.purple,
                }}>{i+1}</div>
                <div style={{flex:1,minWidth:0}}>
                  <div style={{fontFamily:"'IBM Plex Sans',sans-serif",fontSize:15,fontWeight:500,
                    color:T.text,lineHeight:1.35,marginBottom:st.description?10:0}}>
                    <Markdown text={st.title} />
                  </div>
                  {st.description&&(
                    <div style={{fontFamily:"'IBM Plex Sans',sans-serif",fontSize:13,color:T.textDim,lineHeight:1.45}}>
                      <Markdown text={st.description} />
                    </div>
                  )}
                  {hasNote&&!isOpen&&(
                    <div style={{marginTop:5,padding:"4px 8px",borderRadius:4,
                      background:T.amberDim,border:`1px solid ${T.amber}30`,
                      fontFamily:"'IBM Plex Sans',sans-serif",fontSize:13,color:T.amber,lineHeight:1.4}}>
                      📝 {note}
                    </div>
                  )}
                </div>
                {pendingApproval&&!approved&&(
                  <button onClick={()=>setActiveNote(isOpen?null:st.id)} style={{
                    flexShrink:0,padding:"4px 8px",borderRadius:4,border:"none",cursor:"pointer",
                    background:isOpen?(hasNote?T.amberDim:T.purpleDim):"transparent",
                    outline:`1px solid ${isOpen?(hasNote?T.amber+"40":T.purple+"40"):T.border}`,
                    fontFamily:"'JetBrains Mono',monospace",fontSize:10,fontWeight:700,
                    color:isOpen?(hasNote?T.amber:T.purple):T.muted,
                    transition:"all .12s cubic-bezier(0.4, 0, 0.2, 1)",letterSpacing:"0.06em",
                  }}>{hasNote?"EDIT":"NOTE"}</button>
                )}
              </div>

              {/* Per-step feedback textarea */}
              {isOpen&&pendingApproval&&!approved&&(
                <div style={{padding:"0 12px 12px",borderTop:`1px solid ${T.border}`}}>
                  <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:11,color:T.amber,
                    letterSpacing:"0.08em",marginBottom:5,marginTop:8}}>FEEDBACK FOR STEP {i+1}</div>
                  <textarea
                    value={note}
                    onChange={e=>setStepNotes(prev=>({...prev,[st.id]:e.target.value}))}
                    placeholder={`What should change about this step? (e.g. "Use TypeScript instead of JS", "Skip this — not needed")`}
                    aria-label={`Feedback for Step ${i+1}`}
                    rows={2}
                    maxLength={5000}
                    style={{
                      width:"100%",background:T.surfaceHi,border:`1px solid ${T.amber}40`,
                      borderRadius:5,padding:"8px 10px",color:T.text,
                      fontFamily:"'IBM Plex Sans',sans-serif",fontSize:14,lineHeight:1.4,
                      resize:"vertical",outline:"none",boxSizing:"border-box",
                    }}
                    autoFocus
                  />
                  <button onClick={()=>setActiveNote(null)} style={{
                    marginTop:5,padding:"4px 10px",borderRadius:4,border:`1px solid ${T.border}`,
                    background:"transparent",cursor:"pointer",color:T.textDim,
                    fontFamily:"'JetBrains Mono',monospace",fontSize:11,
                  }}>DONE</button>
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Global feedback + actions — only when pending approval */}
      {pendingApproval&&!approved&&(
        <div style={{
          background:T.surface,border:`1px solid ${T.border}`,
          borderRadius:7,padding:"12px 14px",
        }}>
          <div style={{fontFamily:"'JetBrains Mono',monospace",fontSize:11,color:T.textDim,
            letterSpacing:"0.08em",marginBottom:6}}>OVERALL FEEDBACK (optional)</div>
          <textarea
            value={globalNote}
            onChange={e=>setGlobalNote(e.target.value)}
            placeholder="Any overall comments before approving? (e.g. 'Make sure to run tests', 'Keep changes minimal')"
            aria-label="Overall comments or feedback"
            rows={2}
            maxLength={5000}
            style={{
              width:"100%",background:T.surfaceHi,border:`1px solid ${T.border}`,
              borderRadius:5,padding:"8px 10px",color:T.text,
              fontFamily:"'IBM Plex Sans',sans-serif",fontSize:14,lineHeight:1.4,
              resize:"vertical",outline:"none",boxSizing:"border-box",
              transition:"border-color .18s cubic-bezier(0.4, 0, 0.2, 1)",marginBottom:10,
            }}
          />

          {sent&&(
            <div style={{marginBottom:8,padding:"6px 10px",borderRadius:4,
              background:T.brandDim,border:`1px solid ${T.brand}40`,
              fontFamily:"'JetBrains Mono',monospace",fontSize:11,color:T.brand}}>
              ✓ Revision request sent — Jules will update the plan
            </div>
          )}

          <div style={{display:"flex",gap:8}}>
            <Btn
              onClick={handleRequestRevision}
              disabled={!hasFeedback||sending||busy}
              color={T.amber} outline sm
              style={{flex:1}}
            >
              {sending?"SENDING…":`REVISE${annotatedCount>0?` (${annotatedCount} step${annotatedCount>1?"s":""})`:globalNote.trim()?" +note":""}`}
            </Btn>
            <Btn
              onClick={onApprove}
              disabled={busy||sending}
              color={T.purple} sm
              style={{flex:1}}
            >
              <Ic n="approve" s={11} c="#000"/>
              {busy?"APPROVING…":"APPROVE PLAN"}
            </Btn>
          </div>
          <div style={{marginTop:7,fontFamily:"'JetBrains Mono',monospace",fontSize:10,color:T.textDim,textAlign:"center",lineHeight:1.6}}>
            Revise → Jules rewrites the plan · Approve → Jules starts executing
          </div>
        </div>
      )}
    </div>
  );
});
